### ISSUE TITLE
User can add a note for a particular student.

### ISSUE THREAD

**Issue by markodelgadillo** [markodelgadillo/teachers-pet#13]
# Motivation
The user will be able to fill out the provided form text areas and submit the information set to a student.

# Implementation

- [x] Create a div element in html to hold the created divs from javascript.
- [x] created the divs, form and textarea elements with javascript.
- [x] Position and style the newly created elements with css.
- [x] create a button in html
- [x] addEventListener 'click' to button

![screen shot 2017-09-18 at 10 57 15 am](https://user-images.githubusercontent.com/13569476/30556612-43a49024-9c60-11e7-8823-471437afd134.png)

**Comment by ronperris** [comment]
Isn't this still open?
